theme: minima
title: The travelling blog
author: IrinaDG
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome to my travelling blog, where you can meet through me new people, discover new places or embark into a food journey.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
